### ISSUE TITLE
Fun with the Roster

### ISSUE THREAD

**Issue by jo9x** [SCS-ASSE-FS21-Group5/tapas#12]
Two Tasks:

1) Restructure the current Roster implementation -> Outsource the actual HTTP calls in adapters and ports which are called 
2) Notify the auction house about the missing executor -> Trigger startAuction endpoint

TODO: ADR

**Comment by AlexanderLontke** [comment]
Restructuring is done as described above.

Port to trigger Auction is implemented and endpoint in auction house triggered successfully.
