### ISSUE TITLE
Outgoing PATCH requests

### ISSUE THREAD

**Issue by jo9x** [SCS-ASSE-FS21-Group5/tapas#16]
Upon finished execution of a Task we won in an auction, we need to patch the status to this group:
There are two cases:
1)We Patch the result and the status that the task is executed
2) If there is no result -> Just patch the status and leave the result blank

**Comment by MarcoVanini** [comment]
We can now PATCH if a task as been ASSIGNED or EXECUTED.

There are now two out ports, one for TaskAssigned and one for TaskExecuted
