### ISSUE TITLE
Roster Async

### ISSUE THREAD

**Issue by jo9x** [SCS-ASSE-FS21-Group5/tapas#24]
Idea: The task assignment in the Roster may run in a separate Thread -> little code adaptions and performance improvement

**Comment by AlexanderLontke** [comment]
The thread should be invoked by an asynchronous method that implements the following three things:

1. Check whether Executor is available 
2. If not wait 5 minutes then timeout
3. If available send HTTP request to executor and patch returned task to tasklist

**Comment by AlexanderLontke** [comment]
Also Rewrite ADR 10

**Comment by AlexanderLontke** [comment]
https://github.com/SCS-ASSE-FS21-Group5/tapas/commit/0116bdf42398770c7bf53e9e3c167a1f8292a343
